from typing import List, Tuple, Optional, overload

def initialize_env() -> None: ...

class GameState:
    score: int
    available: List[int]
    pieces_left: int
    terminal: bool
    board: int

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pieces: List[int], board_str: str, score: int) -> None: ...
    def check_terminal(self) -> None: ...
    def get_valid_moves(self) -> List[Tuple[int, int]]: ...
    def apply_move(self, slot: int, index: int) -> Optional['GameState']: ...
    def refill_tray(self) -> None: ...

class Node:
    state: GameState
    parent: Optional['Node']
    visits: int
    value_sum: float
    prior: float
    virtual_loss: int
    expanded: bool
    children: List['Node']
    move: Optional[Tuple[int, int]]

    def __init__(self, state: GameState, parent: Optional['Node'] = None, move: Optional[Tuple[int, int]] = None) -> None: ...
    def puct(self, c_puct: float = 1.5) -> float: ...
    def select_child(self) -> Optional['Node']: ...
    def expand(self) -> 'Node': ...
    def backpropagate(self, reward: float) -> None: ...

class EvalRequest:
    node: Node
    state: GameState

class EvalResult:
    node: Node
    value: float
    policy: List[float]
    
    def __init__(self, node: Node, value: float, policy: List[float]) -> None: ...

class AsyncMCTS:
    root: Node

    def __init__(self, root_state: GameState, threads: int = 8, sims: int = 800, c_puct: float = 1.5) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get_requests(self, max_batch: int = 64) -> List[EvalRequest]: ...
    def submit_results(self, results: List[EvalResult]) -> None: ...
    def is_done(self) -> bool: ...
