from typing import overload

import numpy as np
import numpy.typing as npt

def initialize_env() -> None: ...

class GameState:
    score: int
    available: list[int]
    pieces_left: int
    terminal: bool
    board: int
    board_bytes: npt.NDArray[np.uint8]

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pieces: list[int], board_bytes: npt.NDArray[np.uint8], score: int) -> None: ...
    def check_terminal(self) -> None: ...
    def get_valid_moves(self) -> list[tuple[int, int]]: ...
    def apply_move(self, slot: int, index: int) -> GameState | None: ...
    def refill_tray(self) -> None: ...

class Node:
    state: GameState
    parent: Node | None
    visits: int
    value_sum: float
    prior: float
    virtual_loss: int
    expanded: bool
    children: list[Node]
    move: tuple[int, int] | None

    def __init__(self, state: GameState, parent: Node | None = None, move: tuple[int, int] | None = None) -> None: ...
    def puct(self, c_puct: float = 1.5) -> float: ...
    def select_child(self) -> Node | None: ...
    def expand(self) -> Node: ...
    def backpropagate(self, reward: float) -> None: ...
    def apply_dirichlet_noise(self, alpha: float, epsilon: float) -> None: ...

class EvalRequest:
    node: Node
    state: GameState

class EvalResult:
    node: Node
    value: float
    policy: list[float]
    
    def __init__(self, node: Node, value: float, policy: list[float]) -> None: ...

class AsyncMCTS:
    root: Node

    def __init__(self, root_state: GameState, threads: int = 8, sims: int = 800, c_puct: float = 1.5) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get_requests(self, max_batch: int = 64) -> list[EvalRequest]: ...
    def submit_results(self, results: list[EvalResult]) -> None: ...
    def is_done(self) -> bool: ...
